services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: password
      POSTGRES_DB: invenly_db
    ports:
      - "5432:5432"
    volumes:
      - invenly_data:/var/lib/postgresql/data

volumes:
  invenly_data: